### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by inari-ldavey** [lampoona/Terminators-Plant-STARR-seq#2]
Hi, could you provide the versions of the python packages that were used for the analysis? I'm trying to recreate the analysis in `CNN/model_train+evaluate.ipynb`, but I get an error on this cell:

```
term_SeqData = eu.dl.SeqData(
  seqs = data_term['sequence'],
  names = data_term.index,
  seqs_annot = data_term[['enrichment_tobacco', 'enrichment_maize', 'set', 'species']]
)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 term_SeqData = eu.dl.SeqData(
      2   seqs = data_term['sequence'],
      3   names = data_term.index,
      4   seqs_annot = data_term[['enrichment_tobacco', 'enrichment_maize', 'set', 'species']]
      5 )

AttributeError: module 'eugene' has no attribute 'dl'
```

I suspect this is because an older version of eugene was used

**Comment by lampoona** [comment]
can you add: 
"from package eugene import dl"
 before running this portion and see if it imports? 
It's probably a package issue. 

If you want to bypass this, you could write your own dataloader to create a SeqData object to work with. Here is the screenshot from the eugene manaul to assist: 
<img width="739" alt="Screen Shot 2024-11-20 at 12 14 26 PM" src="https://github.com/user-attachments/assets/50be05ce-e095-4305-bcb7-a0d9d1178772">

**Comment by inari-ldavey** [comment]
I didn't have eugene-tools v0.0.6 properly installed
